### ISSUE TITLE
Appveyor: Configured on the previous project version, still relevant ?

### ISSUE THREAD

**Issue by shulard** [friends-of-phpspec/phpspec-code-coverage#1]
The leanphp repository was using Appveyor to check the project on windows. Is this still relevant ? We must ensure that the Appveyor account is tied to at least one active maintainer (aka org maintainer).

There was a `.appveyor.yml` configuration in the project, we must check that everything is fine in it...

- [ ] Validate that Appveyor is still relevant
- [ ] Create / migrate account to use with the project
- [ ] Verify that `.appveyor.yml` is up to date
- [ ] Write doc about appveyor usage (wiki / readme ?)

**Comment by jaylinski** [comment]
I don't see any Windows (or OS specific code in the repo), so I think we don't need AppVeyor. Travis CI should be good enough.

This was the original issue for AppVeyor: https://github.com/leanphp/phpspec-code-coverage/issues/6

**Comment by shulard** [comment]
Ok so, let's wait for users to have trouble on windows (if there any) and will add Appveyor config at that time.

**Comment by shulard** [comment]
Closed by #12.
