### ISSUE TITLE
Update namespace

### ISSUE THREAD

**Issue by samsonasik** [friends-of-phpspec/phpspec-code-coverage#13]
Currently, the namespace is still using `LeanPHP`, how about update the namespace to `FriendsOfPhpspec` with major version update, eg v5 ?

**Comment by shulard** [comment]
Of, course I'm currently working on it 😉.

I plan to introduce the new namespace and mark the old one as deprecated. When the v5 will be released, we'll drop the old one.

**Comment by shulard** [comment]
@samsonasik, take a look at the new v4.3.1 release: https://github.com/friends-of-phpspec/phpspec-code-coverage/tree/v4.3.1

There is a new root namespace: `FriendsOfPhpSpec`. We still maintain the old one to avoid BC Break now but we'll drop that support for the v5 when it'll come.

**Comment by samsonasik** [comment]
Thank you ;)
