### ISSUE TITLE
Support PHP 7.4

### ISSUE THREAD

**Issue by drupol** [friends-of-phpspec/phpspec-code-coverage#16]
It's not possible to install this package when using PHP 7.4

Debug log: https://travis-ci.org/drupol/cas-bundle/jobs/617886217

**Comment by jaylinski** [comment]
Depends on https://github.com/phpspec/phpspec/issues/1268.

**Comment by shulard** [comment]
This issue seems to be fixed by PHPSpec 6.1. @drupol can you check ?

**Comment by drupol** [comment]
Indeed, we can close this one, I just checked.
