### ISSUE TITLE
Please reactivate old repository `drupol/phpspec-code-coverage`

### ISSUE THREAD

**Issue by DavidGarciaCat** [friends-of-phpspec/phpspec-code-coverage#19]
All composer operations worked until the old repository `drupol/phpspec-code-coverage` was removed. Now, Composer throws the following error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

The error appears because the Composer command can't retrieve the deleted vendor and it causes a memory overflow.

To install the new package, I need to delete **all** my vendors and the `composer.lock` file, meaning that all the dependencies that were managed automatically by Composer can't remain the same. This requirement (to fix a Dev dependency) updates all my vendors, even those ones that I don't want to change.

Thus, I kindly ask @drupol to restore the deleted repository (and tags) and then flag it as archived so that no one will face the same problem. Then, anyone can replace the package step-by-step through the commands to prevent unexpected updates for other vendors.

**Comment by drupol** [comment]
Hi,

Have you tried to do the following ?

`$ COMPOSER_MEMORY_LIMIT=2G composer install`

**Comment by DavidGarciaCat** [comment]
Nope. As I said, I needed to delete the lock file to create it again. Doing this, I got updates for many vendors but not a single memory-related error message (and I just needed to change 1 line in the JSON file).

Seems wrong/weird to change a memory parameter when it was never needed until now, when it was not a requirement to re-install all the dependencies, and also bearing in mind that the only thing that has changed is that a repo that was in use has been deleted (or updated to a private one).

**Comment by drupol** [comment]
It's true, it's weird, but I think that is out of scope here. If you have issue while running composer maybe you should open the issue on Composer's issue queue directly.

That said, I won't be able to restore my previously deleted repository.
We moved it to the new realm "friends-of-phpspec" in order to have a central library where people could contribute.

I'm sorry but I cannot help you anymore here.

**Comment by DavidGarciaCat** [comment]
I raised the issue on Composer as per your suggestion. However, I still can see this case as a problem caused by the fact that the deletion of the repository was a "wrong decision" because now no one can retrieve the data that was supposed to be there.

Hope that Composer team can work on a fix for this, but also that this particular case can be used to encourage developers to archive their repositories instead of deleting them.

Cheers,
