### ISSUE TITLE
Certain php functions are not marked as covered

### ISSUE THREAD

**Issue by MichielDilissen** [friends-of-phpspec/phpspec-code-coverage#24]
After running my code coverage, certain php functions are marked as not being covered, although its parameters are covered.
![Screenshot 2020-03-24 08 29 09](https://user-images.githubusercontent.com/22516158/77399644-215f8f00-6daa-11ea-921f-19ca3e2763e9.png)

When I place the same code on one line however, the coverage seems to pick it up as being covered:
![Screenshot 2020-03-24 08 44 17](https://user-images.githubusercontent.com/22516158/77400670-d3e42180-6dab-11ea-9817-5f7bae87389f.png)

I have found this to be the case in multiple php functions such as json_encode, array_merge, array_map, sprintf, ...

I don't know if this can be fixed, but it would hugely improve the visibility of our code coverage.

**Comment by shulard** [comment]
Hello @MichielDilissen !

This kind of behaviour must be related to the coverage driver you are using... This PHPSpec extension is only able to read a Report object, not to generate one.

Which driver are you using ? XDebug ? PCov ?

**Comment by MichielDilissen** [comment]
Hi @shulard 

Thanks for the quick reply. We are using XDebug (version 2.9.1). Do you have any idea how we can fix this? Is it perhaps a setting we need to adjust or do we need to update to the latest version in order for this to work?

**Comment by shulard** [comment]
I'm not sure if updating to latest XDebug will change that behaviour. If your goal is to reach the 100% coverage, I think that you'll need to make your code compatible with the coverage driver.

Maybe you can try another coverage driver like PCov and view if the reported lines are a bit different ?

Also some details about the line coverage analysis difference: https://github.com/krakjoe/pcov#differences-in-reporting

You can still try updating to 2.9.4…

**Comment by MichielDilissen** [comment]
Thank for your help. I will try to experiment further with the suggestions you have given. I will close this issue, since you've indicated this is not related to this package.
