### ISSUE TITLE
Packagist: Publish new package version.

### ISSUE THREAD

**Issue by shulard** [friends-of-phpspec/phpspec-code-coverage#3]
This package must be published on Packagist so we must ensure everything is configured the right way : 

- [x] Update composer.json with organisation name
- [x] Publish the new package with the new name (ensure webhooks are configured)
- [ ] Mark previous project version abandoned ?

**Comment by shulard** [comment]
Hello @seldaek !

Quick question about packagist here, is there a way to mark a project as abandoned without the author ?

A quick note about the context regarding that question :

* We are using a PHPSpec extension "leanphp/phpspec-code-coverage" which is not maintained anymore (https://github.com/leanphp/phpspec-code-coverage/pull/35),
* A lot of people are using that version which is not compatible with PHPSpec 5.0,
* We decide to create a new organization (Friends Of PHPSpec) and host that project to continue maintaining it in a non BC break way,
* We ask if every user of the package can be informed about the new release through the packagist abandoned status…

If you have any other question, please ask me I'll make my best to answer :smile:.

**Comment by shulard** [comment]
Hello @henrikbjorn,

You are the maintainer of the first project on packagist: https://packagist.org/packages/henrikbjorn/phpspec-code-coverage

Can you mark it as abandoned in favored of the new https://packagist.org/packages/friends-of-phpspec/phpspec-code-coverage ?

**Comment by Seldaek** [comment]
I marked both other projects abandoned and pointed to your project. I hope that's fine with @ek9

**Comment by henrikbjorn** [comment]
@Seldaek I already marked mine abandoned. I specifically did not point to another project. I can see you changed that on my "behalf". Will you correct it back again please?

**Comment by Seldaek** [comment]
Sure sorry I assumed that you were also non-responsive here as I didn't see anything. If you rather not point to a specific fork that's fine by me.

**Comment by henrikbjorn** [comment]
@Seldaek Thanks.

**Comment by shulard** [comment]
Thank you for the update @Seldaek ! That was the last point to close this issue :-)
