### ISSUE TITLE
New tag/release ?

### ISSUE THREAD

**Issue by drupol** [friends-of-phpspec/phpspec-code-coverage#32]
Hello colleagues,

Do you think it's a good time for a new tag/release ?

Thanks.

**Comment by jaylinski** [comment]
New tag would be ok for me. But we only did a lot of internal CI stuff:
https://github.com/friends-of-phpspec/phpspec-code-coverage/compare/v4.3.2...master

**Comment by drupol** [comment]
For me the most important thing is: https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/76df1fb695b089c123e9fd0cdbc0ed6cd578ead6

Supporting phpunit/php-code-coverage v8 and its new "branch" features is something I can't wait to test :-)

**Comment by shulard** [comment]
Hello,

This seems a very nice idea :smile:. I think we can tag the 4.4 version. @drupol do you want to write a tiny PR to update the CHANGELOG.md ? Then we'll merge it and create the new release.

**Comment by jaylinski** [comment]
@drupol Friendly bump :)

**Comment by drupol** [comment]
Here's a draft:

## [4.3.3] - 2020-09-07

- Bump drupol/php-conventions. [`#31`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/31)
- Fix LF configuration. [`#30`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/30)
- Support "phpunit/php-code-coverage" v8 [`#27`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/27)
- Various forgotten minor changes [`#28`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/28)
- Switch to GitHub actions [`#25`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/25)
- Update composer.json [`#26`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/26)
- Link build badge to travis-ci.com website [`#23`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/23)
- Fix Travis CI tests with low deps [`#22`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/22)
- Add PHPSPEC v6 support. [`#15`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/15)
- Introduce new root namespace: FriendsOfPhpSpec. [`#14`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/14)
- Remove AppVeyor support since we don't have any windows specific issue. [`#12`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/12)
- Use drupol/php-conventions for code-style and standards. [`#10`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/10)
- External services configuration [`#11`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/11)
- Composer.json: Update project name [`#9`](https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/9)
- CI: Remove PHP 8 for now. [`fc86ff1`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/fc86ff15b5d24dc1a86cf6b22d64adaf20d36de1)
- README: Update badges. [`007ea14`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/007ea14d48539af3a5d475c1d0a920890a3c39bd)
- CS: Remove obsolete phpdoc. [`aa2962f`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/aa2962f101958489345019260b509771d2667802)
- Update composer.json, update PHP constraint and remove obsolete conflicting packages. [`95b5794`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/95b57946e9f75c4afa951b97f7cf31b7b6c7075c)
- Remove Travis configuration file and use default Github actions files. [`11ba5f5`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/11ba5f5c77fc1d414e6258ed4e52025e845e0144)
- Fix PHPStan issues. [`57d7dd4`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/57d7dd478ca21013a3c5a87db749bafd588835cd)
- Remove obsolete phpstan configuration file. [`c765437`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/c7654379a88da46f90e25a0de98c24a7f2c60aa3)
- Fix indentation according to EditorConfig [`c9e12f9`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/c9e12f9d867b8d3412142294a361928fda41045a)
- Fix issues reported by PHPStan [`d3430a9`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/d3430a91c3770c5f72942fe3b3b689e0cd1d0484)
- Reactivate basic tests for CodeCoverageListener [`be6b715`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/be6b715e12be4686128b7df8165def3d3c587c9c)
- Changelog: Describe v4.3.2 [`9a54302`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/9a54302573094cc1b3bdca3cc78c58582130b254)
- Fix codingstyle. [`42ae667`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/42ae667db965fc99c8abaef77bd3fb08f4723244)
- Changelog: Add link to v4.3.1 release. [`6b5e799`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/6b5e799f3ff42d049691f1741185e264145bd0d4)
- Mention PCOV in coverage driver list. [`06c6e7f`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/06c6e7f785ead7345983decf04a776cb1ea9c6a7)
- Changelog: Describe root namespace update. [`48976cc`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/48976cc8a33eb586b90395915423241a3ef7fb0a)
- Add bootstrap to maintain old root namespace alias. [`1a655cb`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/1a655cb44d772442db63b5f978f62e81a5dfbfaf)
- Changelog: Add details for v4.3.0 [`dab6cfd`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/dab6cfd37090317e4f3afbaea60045366330ba8a)
- Update README with new repository name ! [`7d7557c`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/7d7557c898a0668caf4f98f73ba0cfac12e8e964)
- Update .gitattributes. [`263e9b0`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/263e9b0f280c382b7d4ea277c709a085fc3756be)
- Grumphp configuration to enable PHPSpec. [`1892d9b`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/1892d9bbeacd932563c7387164af15350d082a3b)
- Update Travis configuration. [`65ba78c`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/65ba78cfda3739651ea4c52062ecd13c0438a473)
- Update Travis configuration. [`53b3bf7`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/53b3bf7fd5e6d142485a7478edc543b26e27cc3e)
- Update Scrutinizer configuration. [`8a94111`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/8a94111382911d706c3a251ad439ce3a0a8e8b8c)
- Remove obsolete phpcs configuration file. [`e689fbe`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/e689fbe0cc2604e2b1000e4682e2bd423a7cf54b)
- Update coding style and standard. [`6c7cf7d`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/6c7cf7dc769abf457c51d99fc5d3b799ebe69ce3)
- Normalize composer.json file. [`ad3c061`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/ad3c06197cfa09020c15188e3a68edc10c8ba06c)
- Use drupol/php-conventions package in require-dev and remove other obsolete packages. [`bfd341f`](https://github.com/friends-of-phpspec/phpspec-code-coverage/commit/bfd341f9a003ede2573f9a3cc5410defbc2d72e8)

**Comment by shulard** [comment]
There are a lot of tiny changes (and you listed everything since we introduced the new package home), I think that we don't need to add all those details in the CHANGELOG.md file (and that some are already described in it).

Maybe we can just add those two changes :

* Support "phpunit/php-code-coverage" v8 (cf #27)
* Switch to GitHub actions (cf #25)

**Comment by drupol** [comment]
Fair enough :-)

We could also think about automatizing the changelog like in https://github.com/loophp/collection :-)

**Comment by shulard** [comment]
I'm not against automating the changelog but our current commit message structure is not really clean (to be injected inside the CHANGELOG.md file :smile:).

However with the splitted "Merged" / "Commits" section it seems really clean ! We can give it a try, what kind of updated those is require ? Only adding a new action in the workflow ?

**Comment by drupol** [comment]
> I'm not against automating the changelog but our current commit message structure is not really clean (to be injected inside the CHANGELOG.md file smile).

Indeed, that's the first thing to sort out. I'm using this Jetbrains plugin since 2 weeks: https://plugins.jetbrains.com/plugin/9861-git-commit-template it helps me enforcing a proper git commit message.

> However with the splitted "Merged" / "Commits" section it seems really clean ! We can give it a try, what kind of updated those is require ? Only adding a new action in the workflow ?

Then, in order to generate the changelog, I'm using a NodeJS contrib package: https://www.npmjs.com/package/auto-changelog
I wasn't able to find the PHP counterpart (_I think it should not be that difficult to do... I keep that in a corner of my head_).

Then, we just have to update the Github actions, see: https://github.com/loophp/collection/blob/master/.github/workflows/release.yaml

**Comment by shulard** [comment]
Ok, if we need to enforce a proper git commit message, we must document the structure and the different patterns. If you want to make a PR with those changes we'll merge it (I don't care to use a NodeJS contrib package in that case, but building something like that in PHP can be useful ^^).

However, I think that we can reserve this change for a next release and we can just make the 4.3.3 tag now after a tiny CHANGELOG.md update.

**Comment by stelgenhof** [comment]
Not to spoil the next release plans but PHPCoverage is already at v9 :)

**Comment by stelgenhof** [comment]
fyi: `phpunit/php-code-coverage` is now at v9

**Comment by shulard** [comment]
A v5.0.0 release was published with phpspec v7 support. This release force to use PHP7.2+ but a v4.3.3 is on the go (cf #38).

@stelgenhof we'll work on `phpunit/php-code-coverage` v9 support soon.
