### ISSUE TITLE
Tag 5.0.0 versus v5.0.0

### ISSUE THREAD

**Issue by jaylinski** [friends-of-phpspec/phpspec-code-coverage#41]
Hi!

I just noticed that we have two 5.0.0 tags:

* https://github.com/friends-of-phpspec/phpspec-code-coverage/releases/tag/5.0.0
* https://github.com/friends-of-phpspec/phpspec-code-coverage/releases/tag/5.0.1
* https://github.com/friends-of-phpspec/phpspec-code-coverage/releases/tag/v5.0.0

Should we delete those older 5.0.x tags? :thinking: 
The 5.0.1 tag is already published on Packagist.org. I gues the 5.0.0 tag got overwritten by the v5.0.0 tag. I'm not sure if it would break stuff if we would just delete the old tags. Maybe we should release a v5.0.1 tag to "overwrite" the 5.0.1 tag? Or release a v5.0.2 tag?

**Comment by shulard** [comment]
Hello !

That's weird, those old tags were created before migrating in the Friends of PHPSpec new home ^^. I just dropped the old tags and removed the invalid reference from Packagist.

Let's see if we get some complaint about those versions by some users !
