### ISSUE TITLE
There is no available coverage driver to be used? Php7.3 Only?

### ISSUE THREAD

**Issue by klodoma** [friends-of-phpspec/phpspec-code-coverage#42]
I have a project and when I use `"friends-of-phpspec/phpspec-code-coverage": "^6.0"` then it fails in Travis CI for php 7.3. The same configuration passes for php7.4. 

If i use `"friends-of-phpspec/phpspec-code-coverage": "^5.0"` then it works.

I get this error:

![Screenshot_139](https://user-images.githubusercontent.com/944350/100863044-44435680-3494-11eb-84c2-819bb1621d33.png)

```
0.09s$ vendor/bin/phpspec run
In CodeCoverageExtension.php line 60:
                                                     
  There is no available coverage driver to be used.  
                                                     
In Xdebug3Driver.php line 65:
                                                              
  XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set  
                                                              
run [-f|--format FORMAT] [--stop-on-failure] [--no-code-generation] [--no-rerun] [--fake] [-b|--bootstrap BOOTSTRAP] [--no-coverage] [--] [<spec>]
The command "vendor/bin/phpspec run" exited with 1.
cache.2
store build cache
```

You can find the whole source code/configurations here:

https://github.com/klodoma/portphp-steps/tree/phpspec-fail

**Comment by shulard** [comment]
Hello !

That's a weird issue, on our side the PHP7.3 tests are passing. The error came from the `Xdebug3Driver` class (in `phpunit/php-code-coverage` package). Have you tried the given suggestion ?

```
XDEBUG_MODE=coverage or xdebug.mode=coverage has to be set
```

**Comment by shulard** [comment]
Maybe you can just try to add a new specific env var for PHP7.3: `XDEBUG_MODE=coverage` ?

**Comment by klodoma** [comment]
Yes, indeed strange. 

I've added 
```
before_script:
  - export XDEBUG_MODE=coverage
```
which seems to fix the problem.

**Comment by klodoma** [comment]
Anyway, fixed for the moment, so closing.

**Comment by jaylinski** [comment]
Seems to be related to https://github.com/sebastianbergmann/php-code-coverage/issues/834.

**Comment by shulard** [comment]
@jaylinski yes you're right. Maybe we can add some details about the different adapters or at least direct the user to some useful links in the README.
