### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by Saeven** [friends-of-phpspec/phpspec-code-coverage#48]
Hello!

First thank you for this lib, it has been a great tool to have in the tool belt for several years!  Are there any plans to support PHP8?

Thank you!

**Comment by shulard** [comment]
Hello !

Thank you for the kind words ^^

Recently we moved to GitHub action and we run our tests on PHP8. We haven't catch any issue yet, have you some trouble with it ? We also don't block installation through composer on a PHP8 environment...

**Comment by shulard** [comment]
Yep I close this one !
