### ISSUE TITLE
PHP Code Sniffer: Move to a more clean check list ?

### ISSUE THREAD

**Issue by shulard** [friends-of-phpspec/phpspec-code-coverage#5]
Currently the project is using an old version of PHPCS sniffs. We should check if moving to a more precise check list like the [`Doctrine Coding Standard`](https://github.com/doctrine/coding-standard) can be interesting.

**Comment by shulard** [comment]
From my pov it's important to use such standards which are maintained and very precise.

**Comment by jaylinski** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer would also be a possibility.

**Comment by shulard** [comment]
Fixed by #10
