### ISSUE TITLE
PHPStan: Introduce static analysis on the project.

### ISSUE THREAD

**Issue by shulard** [friends-of-phpspec/phpspec-code-coverage#6]
Maybe it's too much checks but PHPstan is a very powerful tool... I think it's relevant to use it.

**Comment by jaylinski** [comment]
As far as I can see we are already using PHPStan via GrumPHP with this config from @drupol:

* https://github.com/friends-of-phpspec/phpspec-code-coverage/blob/master/grumphp.yml.dist#L2
* https://github.com/drupol/php-conventions/blob/master/config/php71/grumphp.yml

:thinking:

**Comment by shulard** [comment]
Yes you are right !
I close this one 😄.

@drupol, it’s still a bit obscure to me to view what kind of checks are applied on the project. Maybe we can add some docs are a link to your repo doc for advanced users ?

**Comment by drupol** [comment]
Hi guys,

Attached the patch to get rid of the file `phpstan.neon`: 
[phpstan.txt](https://github.com/friends-of-phpspec/phpspec-code-coverage/files/4053010/phpstan.txt)

So, to reply to your question now.
I do understand that you might find `[drupol/php-conventions](https://github.com/drupol/php-conventions)` a bit obscure but I will try to be concise.

I made that package to have a kind of consistency across [all the packages](https://github.com/drupol) that I'm publishing.

It only provides a default configuration for [Grumphp](https://github.com/phpro/grumphp).
Grumphp has been created by @veewee and it's a PHP code-quality tool.
I really like it and I'm trying to use it everywhere I can, especially when you work in a team, it allows you to set in the stone the decision and discussion that you can have about code style, commit style etc etc etc... and believe me, there's a huge amount of time that can be lost there.
Here at the European Commission we are using it extensively.

drupol/php-conventions contains a default Grumphp configuration and it can be extended at will through a local grumphp.yml.dist file.

friends-of-phpspec/phpspec-code-coverage uses [the php 7.1 configuration](https://github.com/drupol/php-conventions/blob/master/config/php71/grumphp.yml).
It's a yaml file and it's quite easy to understand what is going on there.
There's a list of tasks that Grumphp will run and you can find each of them [here](https://github.com/phpro/grumphp/tree/master/doc/tasks) and their documentation as well.

Let me know if you need more information, I can adjust things here and there if needed.

**Comment by jaylinski** [comment]
@drupol Can you open a PR for your attached patch?
